// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyajlCk3QmZw1L2XP0GgKDlts9KpNDnHI',
    appId: '1:951551760211:web:3f61f3aa52c264ed1b73a6',
    messagingSenderId: '951551760211',
    projectId: 'scancalo-9ca41',
    authDomain: 'scancalo-9ca41.firebaseapp.com',
    storageBucket: 'scancalo-9ca41.firebasestorage.app',
    measurementId: 'G-HG84MG50H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxjxQZGZ_fwP4WongPsstUJsyuqXCCPjg',
    appId: '1:951551760211:android:47be2b86bd1bd09e1b73a6',
    messagingSenderId: '951551760211',
    projectId: 'scancalo-9ca41',
    storageBucket: 'scancalo-9ca41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6sIjPd3DZET7_27qo1ZxE2yXAn9RC0NU',
    appId: '1:951551760211:ios:a3468c513b9f07061b73a6',
    messagingSenderId: '951551760211',
    projectId: 'scancalo-9ca41',
    storageBucket: 'scancalo-9ca41.firebasestorage.app',
    iosBundleId: 'com.parrel.scannutri',
  );
}
